visitflushing/config/routes.rb
Rails.application.routes.draw do
  resources :hotels
  resources :clients
  
  root 'clients#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

visitflushing/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

visitflushing/app/models/client.rb
class Client < ApplicationRecord
end

visitflushing/app/models/hotel.rb
class Hotel < ApplicationRecord
end

visitflushing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

visitflushing/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone, :email, :comment)
    end
end

visitflushing/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  # GET /hotels or /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1 or /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels or /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1 or /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1 or /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_params
      params.require(:hotel).permit(:name, :description, :reservationurl, :imageurl, :videourl, :address, :geocode)
    end
end

visitflushing/app/helpers/application_helper.rb
module ApplicationHelper
end

visitflushing/app/helpers/clients_helper.rb
module ClientsHelper
end

visitflushing/app/helpers/hotels_helper.rb
module HotelsHelper
end

visitflushing/app/views/clients/_form.html.erb
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

visitflushing/app/views/clients/_home.html.erb
<header class="w3-display-container w3-content w3-wide" style="max-width:1500px;" id="home">
      <img src="https://visitflushing.com/images/nyc.jpg" alt="NYC">
    <div class="w3-display-middle w3-margin-top w3-center">
  <h1 class="w3-xxlarge w3-grey"><span class="w3-padding w3-black w3-opacity-min"><b>NYC</b></span> <span class="w3-hide-small w3-text-light-grey">from across the river</span></h1>
   </div>
</header>

<div class="w3-top w3-card " style="width:100%">
           <div class="w3-bar w3-white w3-wide w3-card w3-padding-16">
            <h5 class="w3-bar-item"><b>Flushing</b> New York</h5>
             <!-- weather widget start -->
              <a class="w3-bar-item" title="Current Weather" href="https://www.weatherwx.com/forecast/ny/new+york.html" target="_blank"><img style="width: 140px;"
                src="https://www.weatherwx.com/forecast.php?forecast=hourly&place=new+york&state=ny&country=us&config=png&alt=hwitransparentbbb&hwvbg=transparent"
                 alt="Click for the latest New York weather forecast."></a>
                 <!-- weather widget end -->
                  <p class="w3-right w3-bar-item w3-hide-small"> Local Time (ET) <span id="datetime"></p>
                   </div>
                    </div>
                     <!-- Local Time Script -->
                      <script>
                      // Local time function
                     var dt = new Date();
                     document.getElementById("datetime").innerHTML = dt.toLocaleTimeString();
                  </script>
                 <!-- Page content -->
                <div class="w3-content w3-padding" style="max-width:1564px">
              <!-- Project Section  -->
             <div class="w3-container w3-padding-32" id="projects">
            <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Features</h3>
           </div>
  <div class="w3-row-padding">
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-grey w3-padding">Main Street</div>
        <img src="https://visitflushing.com/images/mainSt.jpg" alt="House" style="width:99%">
      </div>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-grey w3-padding">7 Train</div>
        <img src="https://visitflushing.com/images/7-train.jpg" alt="House" style="width:100%">
      </div>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-grey w3-padding">Sky View Mall</div>
        <img src="https://visitflushing.com/images/skyView.jpg" alt="House" style="width:99%">
      </div>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <div class="w3-display-container">
        <div class="w3-display-topleft w3-grey w3-padding">Flushing Meadows</div>
        <img src="https://visitflushing.com/images/meadows.jpg" alt="House" style="width:99%">
      </div>
    </div>
  </div>

  <!-- About Section -->
  <div class="w3-container w3-padding-32" id="about">
    <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">About</h3>
    <p>Multicultural Flushing is home to the city’s largest Chinatown, with bustling sidewalks, a tumult of shops, and eateries serving soup dumplings to Taiwanese pancakes. Korean and Indian cultures are well represented too. Built in 1862, Flushing Town Hall now hosts jazz concerts, and several historic homes date to the 17th and 18th centuries. The Queens Botanical Garden is a 39-acre oasis with a focus on native plants.</p>
  </div>

  <div class="w3-row-padding">
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="https://visitflushing.com/images/Tuliptime3.png" alt="Garden" style="width:100%">
      <h3>Botanical Garden</h3>
      <p class="w3-opacity">Parks & Recreation</p>
      <p>Queens Botanical Garden is a botanical garden located at 43-50 Main Street in Flushing, Queens, New York City. The 39-acre site features rose, bee, herb, wedding, and perennial gardens; an arboretum; an art gallery; and a LEED-certified Visitor & Administration Building.</p>

      <!-- Redirecting to another page + details on hover -->
      <a title="Click for more details about this park" href="index2.html" class="w3-block w3-grey w3-button">More Details</a>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="https://visitflushing.com/images/flushing-ny-map.jpg" alt="Map" style="width:100%">
      <h3>Directions</h3>
      <p class="w3-opacity">Map</p>
      <p>Flushing is located in the heart of Queens. It accessible from the LIE, Grand Central pkwy, Van Wyck expwy and Corss Island Parkway.</p>
      <!-- Redirecting to another page + details on hover -->
      <a title="Click for more details about this map" href="index3.html" class="w3-block w3-grey w3-button">More Details</a>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="https://visitflushing.com/images/restaurant.jpg" alt="Dinner" style="width:100%">
      <h3>Restaurants</h3>
      <p class="w3-opacity">Food</p>
      <p>Little Sheep Mongolian Hot Pot is a restaurant with a purpose. That purpose is to introduce all the of the great culinary traditions and flavors of Mongolia to the people of North America. Little Sheep creates an authentic experience for diners.</p>
      <!-- Redirecting to another page path (/details) + details on hover -->
      <a title="Click to find out about more restaurants" href="index2.html" class="w3-block w3-grey w3-button">More Details</a>
    </div>
    <div class="w3-col l3 m6 w3-margin-bottom">
      <img src="https://visitflushing.com/images/hotels.jpg" alt="Hotel" style="width:100%">
      <h3>Hotels</h3>
      <p class="w3-opacity">Lodging</p>
      <p>Enjoy a variety of features during your stay at Hyatt Place Flushing / LaGuardia Airport, including free shuttle service to and from the LaGuardia airport.</p>
      <!-- Redirecting to another page path (/two) + details on hover -->
      <a title="Click for more hotels in Flushing" href="index3.html" class="w3-block w3-grey w3-button">More Details</a>
    </div>
  </div>


<!-- Image of Citifield -->
<div class="container" style="font-family:corbel;">
  <img src="https://visitflushing.com/images/citifield.jpg" class="w3-margin-bottom" style="width:100%">
    <div class="content">
    <h3><b>Feedback to developer</b></h3>
    <h5><b>Lets get in touch and talk about your next neighborhood portfolio...</b></h5>
      <%= render 'form', client: @client %>
    </div>
   </div>
  <!-- End page content -->
 </div>

<!-- Footer -->
<footer class="w3-center w3-grey w3-padding-16" style="margin-left:-3px">
  <p>Developed by <a class="fa fa-linkedin-square" style="color:#0e76a8" href="https://linkedin.com/in/muhammad-khan-21752a1a6" title="LinkedIn Profile" class="w3-hover-text-navy"> Muhammad Khan</a></p>
</footer>

visitflushing/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

visitflushing/app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.phone %></td>
        <td><%= client.email %></td>
        <td><%= client.comment %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

visitflushing/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'home'%>

<%= link_to 'Back', clients_path %>

visitflushing/app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @client.comment %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

visitflushing/app/views/hotels/_form.html.erb
<%= form_for(hotel) do |f| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :reservationurl %>
    <%= f.text_field :reservationurl %>
  </div>

  <div class="field">
    <%= f.label :imageurl %>
    <%= f.text_field :imageurl %>
  </div>

  <div class="field">
    <%= f.label :videourl %>
    <%= f.text_field :videourl %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :geocode %>
    <%= f.text_field :geocode %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

visitflushing/app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

visitflushing/app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hotels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Reservationurl</th>
      <th>Imageurl</th>
      <th>Videourl</th>
      <th>Address</th>
      <th>Geocode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.description %></td>
        <td><%= hotel.reservationurl %></td>
        <td><%= hotel.imageurl %></td>
        <td><%= hotel.videourl %></td>
        <td><%= hotel.address %></td>
        <td><%= hotel.geocode %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

visitflushing/app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

visitflushing/app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hotel.description %>
</p>

<p>
  <strong>Reservationurl:</strong>
  <%= @hotel.reservationurl %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @hotel.imageurl %>
</p>

<img src="<%= @hotel.imageurl %>" alt="<%= @hotel.name %>" width="500" height="333">

<p>
  <strong>Videourl:</strong>
  <%= @hotel.videourl %>
</p>

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/p4vMRslxSQQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<p>
  <strong>Geocode:</strong>
  <%= @hotel.geocode %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

visitflushing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Visitflushing</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://visitflushing.com/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.0/dist/css/foundation.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>